# Generated by Django 5.0.7 on 2024-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_ip_addres_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store_owner', 'Store Owner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
