# Generated by Django 5.0.7 on 2024-08-11 04:52

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=store.models.PathAndRename('logo'))),
                ('banner', models.ImageField(blank=True, null=True, upload_to=store.models.PathAndRename('banner'))),
            ],
        ),
    ]
