# Generated by Django 5.0.7 on 2024-07-31 18:27

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathAndRename('banner')),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathAndRename('logo')),
        ),
    ]
