# Generated by Django 5.0.7 on 2024-08-01 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_initial'),
        ('products', '0007_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCoupon',
            new_name='UsedCoupon',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('general', 'General'), ('product', 'Product-specific')], default='product', max_length=10),
        ),
    ]
