# Generated by Django 5.0.7 on 2024-08-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
