# Generated by Django 5.0.7 on 2024-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='customer_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
