# Generated by Django 5.0.7 on 2024-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
