# Generated by Django 5.0.7 on 2024-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingaddress_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer_name',
            field=models.CharField(max_length=64),
        ),
    ]
