# Generated by Django 5.0.7 on 2024-08-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shippingaddress_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
