# Generated by Django 5.0.7 on 2024-08-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_address_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_released',
            field=models.BooleanField(default=False),
        ),
    ]
