# Generated by Django 5.0.7 on 2024-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='alt',
            field=models.CharField(default='', max_length=256),
        ),
    ]
